packages:
  - apps/*
  - packages/*
  - packages/plugins/*
  - examples/*

catalog:
  '@types/node': 22.13.10
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  tsdown: 0.14.1
  tsup: 8.5.0
  typescript: 5.7.3
  vitest: 3.2.4

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
