packages:
  - apps/*
  - packages/*
  - packages/plugins/*
  - examples/*

catalog:
  '@arethetypeswrong/cli': 0.18.2
  '@tailwindcss/postcss': 4.1.16
  '@tailwindcss/vite': 4.1.18
  '@types/node': 24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@vitest/coverage-v8': 4.0.16
  '@vitest/ui': 4.0.16
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: 4.1.18
  tsdown: 0.18.4
  tsup: 8.5.1
  typescript: 5.9.3
  vitest: 4.0.16

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
