packages:
  - apps/*
  - packages/*
  - packages/plugins/*
  - examples/*

catalog:
  '@types/node': 24.8.0
  '@vitest/coverage-v8': 4.0.6
  '@vitest/ui': 4.0.6
  tsdown: 0.15.12
  tsup: 8.5.0
  typescript: 5.9.3
  vitest: 4.0.6
  react: 19.2.0
  '@types/react': 19.2.2
  'react-dom': 19.2.0
  '@types/react-dom': 19.2.2
  tailwindcss: 4.1.16
  '@tailwindcss/postcss': 4.1.16
  '@tailwindcss/vite': 4.1.16

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
