packages:
  - apps/*
  - packages/*
  - packages/plugins/*
  - examples/*

catalog:
  '@arethetypeswrong/cli': 0.18.2
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/vite': 4.2.1
  '@types/node': 24.11.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitest/coverage-v8': 4.0.18
  '@vitest/ui': 4.0.18
  react: 19.2.4
  react-dom: 19.2.4
  tailwindcss: 4.2.1
  tsdown: 0.20.3
  tsup: 8.5.1
  typescript: 5.9.3
  vitest: 4.0.18

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
