packages:
  - apps/*
  - packages/*
  - packages/plugins/*
  - examples/*

catalog:
  '@types/node': 24.8.0
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  tsdown: 0.15.7
  tsup: 8.5.0
  typescript: 5.9.3
  vitest: 3.2.4

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
