import type { ChangeRegion, InterpretResult } from "@blazediff/core-native";
import { compareImagesGMSD, imagesMatchGMSD } from "./compare/gmsd";
import { compareImages, imagesMatch } from "./compare/pixel";
import { defineConfig } from "./config";
import {
  readDiffMeta,
  ScreenshotFileSystem,
  toDiffMetaPath,
} from "./filesystem";
import { mapWithConcurrency } from "./mapWithConcurrency";
import type { Plugin, PluginDef, PluginFunction, PluginTask } from "./plugin";
import {
  CaptureRunner,
  type CaptureRunnerOptions,
} from "./runner/CaptureRunner";
import {
  didScreenshotFail,
  filterTasks,
  getDeletedScreenshots,
  selectTasks,
  toTaskStatus,
} from "./runner/tasks";
import {
  type PluginCaptureResult,
  type RunDetail,
  type RunEvent,
  type RunEventListener,
  type RunEventType,
  type RunLogLevel,
  type RunnablePlugin,
  type RunState,
  type RunSummary,
  type SerializedError,
  type StartRunRequest,
  type Target,
  type TaskFailure,
  type TaskRecord,
  type TaskStatus,
  toSerializedError,
} from "./runner/types";
import ScreenshotTool, {
  type ScreenshotCaptureDetails,
  type ScreenshotCaptureExtras,
  type ScreenshotCaptureResult,
  type ScreenshotVariantCaptureDetails,
} from "./screenshot";
import { collectScreenshots } from "./screenshots/collectScreenshots";
import { groupScreenshots } from "./screenshots/groupScreenshots";
import type {
  ChangedScreenshot,
  ConfigEnv,
  DeletedScreenshot,
  DiffConfig,
  DiffConfigGMSD,
  DiffMetadata,
  DiffOptions,
  DiffOptionsGMSD,
  DiffOptionsPixel,
  FailedScreenshot,
  NewScreenshot,
  PassedScreenshot,
  Screenshot,
  ScreenshotOptions,
  ScreenshotSettings,
  ScreenshotVariant,
  ScreenshotVariantWithUrl,
  UserConfig,
  Viewport,
} from "./types";

export {
  CaptureRunner,
  type CaptureRunnerOptions,
  type ChangedScreenshot,
  type ChangeRegion,
  type ConfigEnv,
  collectScreenshots,
  compareImages,
  compareImagesGMSD,
  type DeletedScreenshot,
  type DiffConfig,
  type DiffConfigGMSD,
  type DiffMetadata,
  type DiffOptions,
  type DiffOptionsGMSD,
  type DiffOptionsPixel,
  defineConfig,
  didScreenshotFail,
  type FailedScreenshot,
  filterTasks,
  getDeletedScreenshots,
  groupScreenshots,
  type InterpretResult,
  imagesMatch,
  imagesMatchGMSD,
  mapWithConcurrency,
  type NewScreenshot,
  type PassedScreenshot,
  type Plugin,
  type PluginCaptureResult,
  type PluginDef,
  type PluginFunction,
  type PluginTask,
  type RunDetail,
  type RunEvent,
  type RunEventListener,
  type RunEventType,
  type RunLogLevel,
  type RunnablePlugin,
  type RunState,
  type RunSummary,
  readDiffMeta,
  type Screenshot,
  type ScreenshotCaptureDetails,
  type ScreenshotCaptureExtras,
  type ScreenshotCaptureResult,
  ScreenshotFileSystem,
  type ScreenshotOptions,
  type ScreenshotSettings,
  ScreenshotTool,
  type ScreenshotVariant,
  type ScreenshotVariantCaptureDetails,
  type ScreenshotVariantWithUrl,
  type SerializedError,
  type StartRunRequest,
  selectTasks,
  type Target,
  type TaskFailure,
  type TaskRecord,
  type TaskStatus,
  toDiffMetaPath,
  toSerializedError,
  toTaskStatus,
  type UserConfig,
  type Viewport,
};
