import { compareImagesGMSD, imagesMatchGMSD } from "./compare/gmsd";
import { compareImages, imagesMatch } from "./compare/pixel";
import { defineConfig } from "./config";
import { ScreenshotFileSystem } from "./filesystem";
import type { Plugin, PluginDef, PluginFunction } from "./plugin";
import ScreenshotTool, {
  type ScreenshotCaptureDetails,
  type ScreenshotCaptureExtras,
  type ScreenshotCaptureResult,
  type ScreenshotVariantCaptureDetails,
} from "./screenshot";
import type {
  ChangedScreenshot,
  ConfigEnv,
  DeletedScreenshot,
  DiffConfig,
  DiffConfigGMSD,
  DiffOptions,
  DiffOptionsGMSD,
  DiffOptionsPixel,
  FailedScreenshot,
  NewScreenshot,
  PassedScreenshot,
  Screenshot,
  ScreenshotOptions,
  ScreenshotSettings,
  ScreenshotVariant,
  ScreenshotVariantWithUrl,
  UserConfig,
  Viewport,
} from "./types";

export {
  type ChangedScreenshot,
  type ConfigEnv,
  compareImages,
  compareImagesGMSD,
  type DeletedScreenshot,
  type DiffConfig,
  type DiffConfigGMSD,
  type DiffOptions,
  type DiffOptionsGMSD,
  type DiffOptionsPixel,
  defineConfig,
  type FailedScreenshot,
  imagesMatch,
  imagesMatchGMSD,
  type NewScreenshot,
  type PassedScreenshot,
  type Plugin,
  type PluginDef,
  type PluginFunction,
  type Screenshot,
  type ScreenshotCaptureDetails,
  type ScreenshotCaptureExtras,
  type ScreenshotCaptureResult,
  ScreenshotFileSystem,
  type ScreenshotOptions,
  type ScreenshotSettings,
  ScreenshotTool,
  type ScreenshotVariant,
  type ScreenshotVariantCaptureDetails,
  type ScreenshotVariantWithUrl,
  type UserConfig,
  type Viewport,
};
