import type {
  ChangeRegion,
  InterpretResult,
} from "@blazediff/interpret-native";
import { compareImagesGMSD, imagesMatchGMSD } from "./compare/gmsd";
import { compareImages, imagesMatch } from "./compare/pixel";
import { defineConfig } from "./config";
import { LocalEngine, type LocalEngineOptions } from "./engine/LocalEngine";
import { RunStore, type RunStoreOptions } from "./engine/RunStore";
import {
  type ApproveResult,
  type CaptureEngine,
  type EmittableWatchEvent,
  ENGINE_ERROR_CODES,
  isRunInProgressError,
  isUnknownTargetsError,
  isWatchInProgressError,
  type ListTargetsOptions,
  type PluginInfo,
  RunInProgressError,
  type ScreenshotQuery,
  type StartWatchRequest,
  type SubscribeOptions,
  UnknownTargetsError,
  type WatchChange,
  type WatchEvent,
  type WatchEventType,
  WatchInProgressError,
  type WatchScope,
  type WatchStatus,
} from "./engine/types";
import { WarmBrowser, type WarmBrowserOptions } from "./engine/WarmBrowser";
import {
  type CreateFileWatcher,
  DEFAULT_DEBOUNCE_MS,
  DEFAULT_IGNORED_DIRS,
  DEFAULT_MAX_TASKS,
  type FileWatcher,
  WatchSession,
  type WatchSessionOptions,
} from "./engine/WatchSession";
import {
  readDiffMeta,
  ScreenshotFileSystem,
  toDiffMetaPath,
} from "./filesystem";
import { mapWithConcurrency } from "./mapWithConcurrency";
import type {
  Plugin,
  PluginDef,
  PluginFunction,
  PluginTask,
  PluginWatch,
  PluginWatchResolve,
} from "./plugin";
import {
  CaptureRunner,
  type CaptureRunnerOptions,
} from "./runner/CaptureRunner";
import {
  didScreenshotFail,
  filterTasks,
  getDeletedScreenshots,
  selectTasks,
  toTaskStatus,
} from "./runner/tasks";
import {
  type PluginCaptureResult,
  type RunDetail,
  type RunEvent,
  type RunEventListener,
  type RunEventType,
  type RunLogLevel,
  type RunnablePlugin,
  type RunState,
  type RunSummary,
  type RunTrigger,
  type SerializedError,
  type StartRunRequest,
  type Target,
  type TaskFailure,
  type TaskRecord,
  type TaskStatus,
  toSerializedError,
} from "./runner/types";
import ScreenshotTool, {
  type ScreenshotCaptureDetails,
  type ScreenshotCaptureExtras,
  type ScreenshotCaptureResult,
  type ScreenshotCaptureSink,
  type ScreenshotVariantCaptureDetails,
} from "./screenshot";
import { collectScreenshots } from "./screenshots/collectScreenshots";
import { groupScreenshots } from "./screenshots/groupScreenshots";
import {
  type CaptureManifest,
  MANIFEST_FILENAME,
  MANIFEST_VERSION,
  mergeCaptureManifest,
  readCaptureManifest,
  recordCaptureOrigins,
  type ScreenshotOrigin,
  toManifestKey,
} from "./screenshots/manifest";
import {
  FsScreenshotStore,
  type ScreenshotBucket,
  type ScreenshotStore,
} from "./store";
import type {
  ChangedScreenshot,
  ConfigEnv,
  DeletedScreenshot,
  DiffConfig,
  DiffConfigGMSD,
  DiffMetadata,
  DiffOptions,
  DiffOptionsGMSD,
  DiffOptionsPixel,
  FailedScreenshot,
  NewScreenshot,
  PassedScreenshot,
  Screenshot,
  ScreenshotOptions,
  ScreenshotSettings,
  ScreenshotVariant,
  ScreenshotVariantWithUrl,
  UserConfig,
  Viewport,
} from "./types";

export {
  type ApproveResult,
  type CaptureEngine,
  type CaptureManifest,
  CaptureRunner,
  type CaptureRunnerOptions,
  type ChangedScreenshot,
  type ChangeRegion,
  type ConfigEnv,
  type CreateFileWatcher,
  collectScreenshots,
  compareImages,
  compareImagesGMSD,
  DEFAULT_DEBOUNCE_MS,
  DEFAULT_IGNORED_DIRS,
  DEFAULT_MAX_TASKS,
  type DeletedScreenshot,
  type DiffConfig,
  type DiffConfigGMSD,
  type DiffMetadata,
  type DiffOptions,
  type DiffOptionsGMSD,
  type DiffOptionsPixel,
  defineConfig,
  didScreenshotFail,
  type EmittableWatchEvent,
  ENGINE_ERROR_CODES,
  type FailedScreenshot,
  type FileWatcher,
  FsScreenshotStore,
  filterTasks,
  getDeletedScreenshots,
  groupScreenshots,
  type InterpretResult,
  imagesMatch,
  imagesMatchGMSD,
  isRunInProgressError,
  isUnknownTargetsError,
  isWatchInProgressError,
  type ListTargetsOptions,
  LocalEngine,
  type LocalEngineOptions,
  MANIFEST_FILENAME,
  MANIFEST_VERSION,
  mapWithConcurrency,
  mergeCaptureManifest,
  type NewScreenshot,
  type PassedScreenshot,
  type Plugin,
  type PluginCaptureResult,
  type PluginDef,
  type PluginFunction,
  type PluginInfo,
  type PluginTask,
  type PluginWatch,
  type PluginWatchResolve,
  type RunDetail,
  type RunEvent,
  type RunEventListener,
  type RunEventType,
  RunInProgressError,
  type RunLogLevel,
  type RunnablePlugin,
  type RunState,
  RunStore,
  type RunStoreOptions,
  type RunSummary,
  type RunTrigger,
  readCaptureManifest,
  readDiffMeta,
  recordCaptureOrigins,
  type Screenshot,
  type ScreenshotBucket,
  type ScreenshotCaptureDetails,
  type ScreenshotCaptureExtras,
  type ScreenshotCaptureResult,
  type ScreenshotCaptureSink,
  ScreenshotFileSystem,
  type ScreenshotOptions,
  type ScreenshotOrigin,
  type ScreenshotQuery,
  type ScreenshotSettings,
  type ScreenshotStore,
  ScreenshotTool,
  type ScreenshotVariant,
  type ScreenshotVariantCaptureDetails,
  type ScreenshotVariantWithUrl,
  type SerializedError,
  type StartRunRequest,
  type StartWatchRequest,
  type SubscribeOptions,
  selectTasks,
  type Target,
  type TaskFailure,
  type TaskRecord,
  type TaskStatus,
  toDiffMetaPath,
  toManifestKey,
  toSerializedError,
  toTaskStatus,
  UnknownTargetsError,
  type UserConfig,
  type Viewport,
  WarmBrowser,
  type WarmBrowserOptions,
  type WatchChange,
  type WatchEvent,
  type WatchEventType,
  WatchInProgressError,
  type WatchScope,
  WatchSession,
  type WatchSessionOptions,
  type WatchStatus,
};
