name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/docs/**'
      - '.github/workflows/deploy-docs.yml'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Astro docs site
        uses: withastro/action@v2
        with:
          path: apps/docs
          node-version: 20
          package-manager: pnpm@10.16.1
          github-token: ${{ secrets.GITHUB_TOKEN }}
